---
title: "CodeBook"
output: html_document
---

#Data
Human Activity Recognition Using Smartphones Dataset
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

#Analysis
The data provided contained test data (30%) and training data (70%). Each set contained
3 sets of data: 1) subject data, 2) activity type data, and 3) measurement data. 

For both the training set and the test set, the 3 data sets underneath were combined.
Once the 3 data sets were combined, the 2 combined data sets (training and test) were
merged into one.  The number of columns was then reduced to only contain the values
that calculated mean and standard deviation.  The data was then grouped by the subject
and then the activity_type and then the average of each column in the data set was 
calculated.

# Variables

1. subject  
values - 1:30  
class - integer  
description - each number represents the person that the data was collected from  

2. activity_type  
values - Walking, Walking Upstairs, Walking Downstairs, Laying, Standing, Sitting  
class - character  
description - the activity for which the data was collected  

3. tBodyAcc-mean()-X  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean in the X direction for the time signal for Body Acceleration  

4. tBodyAcc-mean()-Y  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean in the Y direction for the time signal for Body Acceleration  

5. tBodyAcc-mean()-Z  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean in the Z direction for the time signal for Body Acceleration  

6. tGravityAcc-mean()-X  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean in the X direction for the time signal for Gravity Acceleration  

7. tGravityAcc-mean()-Y  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean in the Y direction for the time signal for Gravity Acceleration  

8. tGravityAcc-mean()-Z  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean in the Z direction for the time signal for Gravity Acceleration  
  
9. tBodyAccJerk-mean()-X   
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Jerk Acceleration in the X direction  

10. tBodyAccJerk-mean()-Y  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Jerk Acceleration in the Y direction  

11. tBodyAccJerk-mean()-Z  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Jerk Acceleration in the Z direction  

12. tBodyGyro-mean()-X  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Gyroscope in the X direction  

13. tBodyGyro-mean()-Y  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Gyroscope in the Y direction  

14. tBodyGyro-mean()-Z  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Gyroscope in the Z direction  

15. tBodyGyroJerk-mean()-X  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Gyroscopic Jerk in the X direction  

16. tBodyGyroJerk-mean()-Y  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Gyroscopic Jerk in the Y direction   

17. tBodyGyroJerk-mean()-Z  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Gyroscopic Jerk in the Z direction  

18. tBodyAccMag-mean()  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Acceleration Magnitude  

19. tGravityAccMag-mean()  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Gravity Acceleration Magnitude  

20. tBodyAccJerkMag-mean()  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Acceleration Jerk Magnitude  

21. tBodyGyroMag-mean()  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Gyroscopic Magnitude  

22. tBodyGyroJerkMag-mean()  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean time signal for Body Gyroscopic Jerk Magnitude  

23. fBodyAcc-mean()-X  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Acceleration in the X direction  

24. fBodyAcc-mean()-Y  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Acceleration in the Y direction  

25. fBodyAcc-mean()-Z  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Acceleration in the Z direction   

26. fBodyAccJerk-mean()-X  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Acceleration Jerk in the X direction  

27. fBodyAccJerk-mean()-Y  
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Acceleration Jerk in the Y direction  

28. fBodyAccJerk-mean()-Z  
values - normailzed value between [-1, 1]  
class - numeric   
description - mean frequency signal for Body Acceleration Jerk in the Z direction

29. fBodyGyro-mean()-X
values - normailzed value between [-1, 1]
class - numeric
description - mean frequency signal for Body Gyroscope in the X direction

30. fBodyGyro-mean()-Y
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Gyroscope in the Y direction  

31. fBodyGyro-mean()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Gyroscope in the Z direction  

32. fBodyAccMag-mean()
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Acceleration Magnitude  

33. fBodyBodyAccJerkMag-mean()
values - normailzed value between [-1, 1] 
class - numeric  
description - mean frequency signal for Body Acceleration Jerk Magnitude  

34. fBodyBodyGyroMag-mean()
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Gyroscopic Magnitude   

35. fBodyBodyGyroJerkMag-mean()
values - normailzed value between [-1, 1]  
class - numeric  
description - mean frequency signal for Body Gyroscopic Jerk Magnitude   

36. tBodyAcc-std()-X
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Acceleration in the X direction  

37. tBodyAcc-std()-Y
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Acceleration in the Y direction  

38. tBodyAcc-std()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Acceleration in the Z direction  

39. tGravityAcc-std()-X
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Gravity Acceleration in the X direction  

40. tGravityAcc-std()-Y
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Gravity Acceleration in the Y direction  

41. tGravityAcc-std()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Gravity Acceleration in the Z direction  

42. tBodyAccJerk-std()-X
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Acceleration Jerk in the X direction    

43. tBodyAccJerk-std()-Y
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Acceleration Jerk in the Y direction  

44. tBodyAccJerk-std()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Acceleration Jerk in the Z direction  

45. tBodyGyro-std()-X
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Gyroscope in the X direction  

46. tBodyGyro-std()-Y
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Gyroscope in the Y direction   

47. tBodyGyro-std()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Gyroscope in the Z direction    

48. tBodyGyroJerk-std()-X
values - normailzed value between [-1, 1]  
class - numeric 
description - standard deviation time signal for Body Gyroscopic Jerk in the X direction    

49. tBodyGyroJerk-std()-Y
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Gyroscopic Jerk in the Y direction  

50. tBodyGyroJerk-std()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Gyroscopic Jerk in the Z direction  

51. tBodyAccMag-std()
values - normailzed value between [-1, 1]   
class - numeric  
description - standard deviation time signal for Body Acceleration Magnitude   

52. tGravityAccMag-std()
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Gravity Acceleration Magnitude  
 
53. tBodyAccJerkMag-std()
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Acceleration Jerk Magnitude  

54. tBodyGyroMag-std()
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation time signal for Body Gyroscopic Magnitude  

55. tBodyGyroJerkMag-std()
values - normailzed value between [-1, 1]  
class - numeric 
description - standard deviation time signal for Body Gyroscopic Jerk Magnitude  

56. fBodyAcc-std()-X
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Acceleration in the X direction  

57. fBodyAcc-std()-Y
values - normailzed value between [-1, 1]  
class - numeric    
description - standard deviation frequency signal for Body Acceleration in the Y direction  

58. fBodyAcc-std()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Acceleration in the Z direction  

59. fBodyAccJerk-std()-X
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Acceleration Jerk in the X direction  

60. fBodyAccJerk-std()-Y
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Acceleration Jerk in the Y direction  

61. fBodyAccJerk-std()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Acceleration Jerk in the Z direction  

62. fBodyGyro-std()-X
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Gyroscope in the X direction  

63. fBodyGyro-std()-Y
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Gyroscope in the Y direction  

64. fBodyGyro-std()-Z
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Gyroscope in the Z direction  

65. fBodyAccMag-std()
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Acceleration Magnitude  

66. fBodyBodyAccJerkMag-std()
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Acceleration Jerk Magnitude  

67. fBodyBodyGyroMag-std()
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Gyroscopic Magnitude  

68. fBodyBodyGyroJerkMag-std()
values - normailzed value between [-1, 1]  
class - numeric  
description - standard deviation frequency signal for Body Gyroscopic Jerk Magnitude  
